server {
  listen 80;
  server_name _;

  location /media/ {
    alias /usr/share/nginx/html/media/;
    try_files $uri $uri/ /media/index.html;
  }

  location /products/ {
    alias /usr/share/nginx/html/products/;
    try_files $uri $uri/ /products/index.html;
  }

  location / {
    root /usr/share/nginx/html/hub;
    try_files $uri $uri/ /index.html;
  }
}
